services:
  nginx-proxy:
    build: nginx
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
  flask-app:
    build: flask
    restart: always
    ports: 
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3